language: python 
python: 
  - "3.8"
install:
  - pip install -e . 
  - pip install pytest-cov codecov # Install packages for code coverage report
script:
  - pytest --cov=src tests
after_success:
  - codecov                        # Upload report to codecov.io

  - name: Codecov
    uses: codecov/codecov-action@v3.1.1
