name: oil-prices
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - pandas
    - numpy
    - matplotlib
    - seaborn
    - jupyter
    - scikit-learn
    - xgboost