name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: oil-prices
        environment-file: environment.yaml
        auto-activate-base: false
    
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda activate oil-prices
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov codecov
    
    - name: Run tests with pytest
      shell: bash -l {0}
      run: |
        conda activate oil-prices
        pytest --cov=src tests
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true